extends: spectral:oas

rules:

  oas3-server-not-example.com: true
  contact-properties: true
  tag-description: true

  oas3-unused-component: true
  oas3-parameter-description: true
  openapi-tags-alphabetical: false

  # TODO: re-enable after switching to OpenAPI 3.1 and using type: 'null' instead of `nullable: true`
  oas3-valid-media-example: false
