extends: spectral:oas

rules:
  oas3-parameter-description: true
  oas3-server-not-example.com: true
  openapi-tags-alphabetical: true
  operation-default-response: true
  contact-properties: true
  tag-description: true
