version: "3"
services:

  app:
    image: tianon/true
    restart: "no"
    depends_on:
      - service

  service:
    network_mode: host
    container_name: golang-service-template.service
    build:
      context: ..
      dockerfile: Containerfile
    env_file:
      - $PWD/.env
      - $PWD/.env.local
