FROM golang:1.14-alpine

WORKDIR /app

ADD go.mod go.sum ./
RUN go mod download

RUN apk add --no-cache ca-certificates \
        dpkg \
        gcc \
        git \
        musl-dev \
        bash

RUN env GO111MODULE=off go get github.com/derekparker/delve/cmd/dlv

CMD ["dlv", "debug", "/app/devstack", "--headless", "--listen=:2345", "--api-version=2", "--continue", "--accept-multiclient"]
