FROM golang:1.14-alpine

WORKDIR /cli

RUN apk add --no-cache ca-certificates \
        dpkg \
        git \
        make \
        gcc \
        musl-dev \
        bash

RUN GO111MODULE=off go get -u github.com/myitcv/gobin
