FROM golang:1.14

# Copy local code to the container image.
WORKDIR /app

RUN GOFLAGS= go get -u github.com/go-delve/delve/cmd/dlv

# Install dependencies
COPY ./go.mod ./go.sum ./
RUN go mod download

# dlv attach --headless --listen=:2345 $(pgrep -f $binary_filepath) --api-version=2
CMD [ "dlv", "debug", "./devstack", "--headless", "--listen=:2345", "--api-version=2", "--continue", "--accept-multiclient" ]
