// Package internal provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/pseudo-su/oapi-ui-codegen DO NOT EDIT.
package internal

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"github.com/getkin/kin-openapi/openapi3"
	"strings"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWTW/bRhD9K4tpDy1Ai3JS9MBbmxqogDYN0NwCHybkkNp0vzw7lCUY/O/F7pK2K8tV",
	"AjSADz2JXO7MvvfmvYXuoPU2eEdOIjR3ENstWcyPV8ye00NgH4hFU15ufUfpt/dsUaAB7eT1K6hADoHK",
	"Kw3EMFVgKUYc8u75YxTWboBpqoDpZtRMHTQfSs+H/df3zfzHT9RK6vXWyzuSp3B0dwzmxx9OgnFoTyGp",
	"QHA4j1B3MLd4HlzBI2Tzw7dMPTTwTf0gcD2rW89kpvtWyIyH9P5yOX4RwZPs0nna9T4VG92SixlsAQ2/",
	"b97nEi0mvf55i8NArNKx4jnZY0cctXfQwOVqvVqn3T6Qw6Chgdd5qYKAss3wauclzJiHomrSFEV7t+mg",
	"AaOjLINLQsTgXSyCv1qvi9WdkMulGILRbS6uP8UEYsnK5806FvodxZZ1kELjJxVwoE5lfZTvVShYtoQd",
	"cUayv3C0zwiOS412fynxSrak0p7cKzV5YFI9gng8+oKmx9HIf0a13BgniI6O9oFaoU7RvKeCOFqLfIAG",
	"ftNRFBqjlpFlw8bkyWXlOlXUZ+c5DzMgoyXJGn44lu5Xf6ssuoPKTk4SMsnITqEo70iJtqS+s7hXl+v1",
	"95A8Cw3cjMSHJR/pMKsFHuenRxPpseJnL8jp+iva7n/Pfabnjgw3u62C4OMJk7VMKHT6zrh8Ktnb0Zh7",
	"ceAF0X+TeShM9J+yX7JW3wWSTTc9m7m49bfvSH4+bLpzsXu/JaW7ZJbknkAyJ4817WhJWbq9H0KWD/9H",
	"yIRH+jeHfeVEnRL6apF5OTjxQrVDo9PazUhRXtLkN673qvesUMVAre51+4wJUhnxbhnnyAYaqAdv0A0X",
	"6Ytu6ULIBoNC9e4SjpG8GZnJifrFW9QOpmppshUJsanruy5/mb6k6R+yJV5aVrBD1vjRlHGXdiWGs9qA",
	"Qa9ojzYYWrXePul35YRYtWMUb1VpkK845GEe+GPUTZ2Dkf6RrGL5i7LSPuGcrqe/AwAA///mA983TQsA",
	"AA==",
}

// GetOpenAPISpec returns the Swagger specification corresponding to the generated code
// in this file.
func GetOpenAPISpec() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
