// Package pkg provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/pseudo-su/oapi-codegen DO NOT EDIT.
package pkg

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Pet defines model for Pet.
type Pet struct {
	Id   int64   `json:"id"`
	Name string  `json:"name"`
	Tag  *string `json:"tag,omitempty"`
}

// Pets defines model for Pets.
type Pets []Pet

// ListPetsParams defines parameters for ListPets.
type ListPetsParams struct {
	Limit *int32 `json:"limit,omitempty"`
}
