name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.16.0
        env GO111MODULE=off go get -u github.com/myitcv/gobin
        go mod download

    - name: Lint
      run: |
        ./bin/golangci-lint run ./...
        docker run --rm -it stoplight/spectral lint "./openapi.yaml"

    - name: Unit Test
      run: |
        make report-test-unit

    - name: Integration Test
      run: |
        docker-compose run --rm tools make report-test-integration

    - name: Build
      run: go build -v -o golang-service-template ./cmd
