name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      id: go
      uses: actions/setup-go@v2-beta
      with:
        go-version: 1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        make setup

    - name: Ensure consistent/idempotent code generation
      run: |
        go generate ./...
        COUNT=$(git status --porcelain | wc -l)
        echo "$COUNT lines changed after running \"go generate ./...\""
        exit $COUNT

    - name: Lint Go code
      run: |
        ./bin/golangci-lint run ./...

    - name: Lint OpenAPI spec
      run: |
        ./bin/spectral lint --fail-severity=warn ./openapi.yaml

    - name: Unit Test
      run: |
        make report-test-unit

    - name: Integration Test
      run: |
        docker-compose run --rm tools make report-test-integration

    - name: Build
      run: go build -v -o golang-service-template ./cmd
